---
- template:
    src: php-fpm.conf.j2
    dest: "{{ php_dir }}/{{ version }}/etc/php-fpm.conf"
    owner: root
    group: root
    mode: 0644

- file:
    path: "{{ php_dir }}/{{ version }}/etc/php-fpm.d/www.conf"
    state: absent

- file:
    path: "{{ php_dir }}/{{ version }}/etc/php-fpm.d/www.conf.default"
    state: absent

- file:
    path: "{{ php_dir }}/{{ version }}/etc/php-fpm.d/"
    state: directory
    owner: root
    group: root
    mode: 0755

- template:
    src: www.conf.j2
    dest: "{{ php_dir }}/{{ version }}/etc/php-fpm.d/{{ item.value.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ www }}"
  notify: "restart_phpfpm_{{ version }}_service"

- import_role:
    name: youyo.upstart
  vars:
    upstart_name: "phpfpm-{{ version }}"
    upstart_description: "phpfpm-{{ version }}"
    upstart_exec: "{{ php_dir }}/{{ version }}/sbin/php-fpm --nodaemonize --allow-to-run-as-root"
    upstart_respawn: yes

- service:
    name: "phpfpm-{{ version }}"
    enabled: yes
    state: started
