---
- name: Configuration for php-fpm.conf
  template:
    src: php-fpm.conf.j2
    dest: "{{ php_dir }}/{{ version }}/etc/php-fpm.conf"
    owner: root
    group: root
    mode: 0644

- name: Delete www.conf,www.conf.default
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ php_dir }}/{{ version }}/etc/php-fpm.d/www.conf"
    - "{{ php_dir }}/{{ version }}/etc/php-fpm.d/www.conf.default"
    - "{{ php_dir }}/{{ version }}/etc/php-fpm.conf.default"

- name: Create directory
  file:
    path: "{{ php_dir }}/{{ version }}/etc/php-fpm.d/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create configuration
  template:
    src: www.conf.j2
    dest: "{{ php_dir }}/{{ version }}/etc/php-fpm.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ www }}"
  notify: "restart_phpfpm_{{ version }}_service"

- name: Setup upstart config
  import_role:
    name: youyo.upstart
  vars:
    upstart_name: "phpfpm-{{ version }}"
    upstart_description: "phpfpm-{{ version }}"
    upstart_exec: "{{ php_dir }}/{{ version }}/sbin/php-fpm --nodaemonize --allow-to-run-as-root"
    upstart_respawn: yes

- name: Start service
  service:
    name: "phpfpm-{{ version }}"
    enabled: yes
    state: started
